In [78]:
from json import loads
import pandas as pd


# 不是完整的 json,是一个 json 集合。 不能直接使用 pd.read_json ,所以创建函数读取数据

def readJsonFile(path, column=['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
                               'report-no', 'categories', 'license', 'abstract', 'versions',
                               'update_date', 'authors_parsed'], col_num=170000):
    data = []
    with open(path) as f:
        for line, json in enumerate(f):
            if line == col_num:
                break
            data.append({col: loads(json)[col] for col in column})
    return pd.DataFrame(data)


df = readJsonFile('../arxiv-metadata-oai-2019.json')
df

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,0704.0297,Sung-Chul Yoon,"Sung-Chul Yoon, Philipp Podsiadlowski and Step...",Remnant evolution after a carbon-oxygen white ...,"15 pages, 15 figures, 3 tables, submitted to M...",None,10.1111/j.1365-2966.2007.12161.x,None,astro-ph,None,We systematically explore the evolution of t...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[[Yoon, Sung-Chul, ], [Podsiadlowski, Philipp,..."
1,0704.0342,Patrice Ntumba Pungu,B. Dugmore and PP. Ntumba,Cofibrations in the Category of Frolicher Spac...,27 pages,None,None,None,math.AT,None,Cofibrations are defined in the category of ...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[[Dugmore, B., ], [Ntumba, PP., ]]"
2,0704.0360,Zaqarashvili,T.V. Zaqarashvili and K Murawski,Torsional oscillations of longitudinally inhom...,"6 pages, 3 figures, accepted in A&A",None,10.1051/0004-6361:20077246,None,astro-ph,None,We explore the effect of an inhomogeneous ma...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[[Zaqarashvili, T. V., ], [Murawski, K, ]]"
3,0704.0525,"Sezgin Ayg\""un","Sezgin Aygun, Ismail Tarhan, Husnu Baysal",On the Energy-Momentum Problem in Static Einst...,This submission has been withdrawn by arXiv ad...,"Chin.Phys.Lett.24:355-358,2007",10.1088/0256-307X/24/2/015,None,gr-qc,None,This paper has been removed by arXiv adminis...,"[{'version': 'v1', 'created': 'Wed, 4 Apr 2007...",2019-10-21,"[[Aygun, Sezgin, ], [Tarhan, Ismail, ], [Baysa..."
4,0704.0535,Antonio Pipino,"Antonio Pipino (1,3), Thomas H. Puzia (2,4), a...",The Formation of Globular Cluster Systems in M...,"32 pages (referee format), 9 figures, ApJ acce...","Astrophys.J.665:295-305,2007",10.1086/519546,None,astro-ph,None,The most massive elliptical galaxies show a ...,"[{'version': 'v1', 'created': 'Wed, 4 Apr 2007...",2019-08-19,"[[Pipino, Antonio, ], [Puzia, Thomas H., ], [M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169995,math/0603044,B\'alint Vet\H{o},B\'alint Vet\H{o},The time evolution of permutations under rando...,15 pages,"Acta Sci. Math. (Szeged) 72 (2006), no. 3-4, 8...",None,None,math.PR,None,"We consider permutations of $\{1,...,n\}$ ob...","[{'version': 'v1', 'created': 'Thu, 2 Mar 2006...",2019-05-20,"[[Vető, Bálint, ]]"
169996,math/0603049,Carlos Florentino,Carlos A. A. Florentino,"Invariants of 2 by 2 matrices, irreducible SL(...",None,Geom. Dedicata 121 (2006) 167-186,10.1007/s10711-006-9097-5,None,math.GT math.RT,None,We obtain an explicit characterization of th...,"[{'version': 'v1', 'created': 'Thu, 2 Mar 2006...",2019-03-11,"[[Florentino, Carlos A. A., ]]"
169997,math/0603124,Alexei Yu. Pirkovskii,A. Yu. Pirkovskii,Approximate characterizations of projectivity ...,12 pages,None,10.1017/S0305004107000163,None,math.FA,None,We characterize projective and injective Ban...,"[{'version': 'v1', 'created': 'Sun, 5 Mar 2006...",2019-05-01,"[[Pirkovskii, A. Yu., ]]"
169998,math/0603268,Najib Ouled Azaiez,Najib Ouled Azaiez,The Ring of Quasimodular Forms for a Cocompact...,"22 pages, 1 figure",Journal of Number Theory 128 (2008) 1966-1988,10.1016/j.jnt.2007.08.004,None,math.NT,None,We describe the additive structure of the gr...,"[{'version': 'v1', 'created': 'Mon, 13 Mar 200...",2019-08-23,"[[Azaiez, Najib Ouled, ]]"
169999,math/0603276,Benjamin McKay,Benjamin McKay (University College Cork),Rigid geometry on projective varieties,27 pages,"Math. Z. 272 (2012), no. 3-4, 761-791",None,None,math.DG math.AG,http://arxiv.org/licenses/nonexclusive-distrib...,We prove rigidity of various types of holomo...,"[{'version': 'v1', 'created': 'Sun, 12 Mar 200...",2019-11-12,"[[McKay, Benjamin, , University College Cork]]"

# 1. 论文摘要和论文标题出现关键词的频率

In [79]:
taget1_df = readJsonFile('../arxiv-metadata-oai-2019.json', column=['id', 'title', 'abstract'])
taget1_df

,id,title,abstract
0,0704.0297,Remnant evolution after a carbon-oxygen white ...,We systematically explore the evolution of t...
1,0704.0342,Cofibrations in the Category of Frolicher Spac...,Cofibrations are defined in the category of ...
2,0704.0360,Torsional oscillations of longitudinally inhom...,We explore the effect of an inhomogeneous ma...
3,0704.0525,On the Energy-Momentum Problem in Static Einst...,This paper has been removed by arXiv adminis...
4,0704.0535,The Formation of Globular Cluster Systems in M...,The most massive elliptical galaxies show a ...
...,...,...,...
169995,math/0603044,The time evolution of permutations under rando...,"We consider permutations of $\{1,...,n\}$ ob..."
169996,math/0603049,"Invariants of 2 by 2 matrices, irreducible SL(...",We obtain an explicit characterization of th...
169997,math/0603124,Approximate characterizations of projectivity ...,We characterize projective and injective Ban...
169998,math/0603268,The Ring of Quasimodular Forms for a Cocompact...,We describe the additive structure of the gr...
169999,math/0603276,Rigid geometry on projective varieties,We prove rigidity of various types of holomo...

In [80]:
# 定义统计函数
def word_count(txt):
    word_dic = {}
    for ch in '''!"$%&()*+,-./;:<=>?@[\\]^_{|}~''\n\t ''':
        txt = txt.replace(ch, ' ')
    for word in txt.split(' '):
        word = word.lower()
        if word_dic.get(word):
            word_dic[word] += 1
        else:
            word_dic[word] = 1
    return word_dic


# 使用停词库过滤掉部分无用词
def wordsfilter(word_dic):
    stopwords = []
    # 读取停词库
    with open('./stopwords.txt') as f:
        for word in f:
            stopwords.append(word.split('\n')[0])
    for word in list(word_dic.keys()):  # 不能在遍历字典的同时修改字典, 所以转换成 list
        if word in stopwords:
            del word_dic[word]
    # 字典可以使用空字符串来作为 key 所以需要特殊处理一下
    del word_dic['']


# worldcloud 库 实现词云图
def creat_wordcloudImg(word_dic, file_name, word_num=50):
    import wordcloud
    img = wordcloud.WordCloud(background_color='white', font_path='msyh.ttc', width=2000, height=1500,
                              max_words=word_num).generate_from_frequencies(word_dic)
    img.to_file(f'./{file_name}.png')


def word_count2df(column):
    word_dic = {}
    for i in range(len(taget1_df)):
        for word in word_count(taget1_df[column][i]):
            if word_dic.get(word):
                word_dic[word] += 1
            else:
                word_dic[word] = 1
    wordsfilter(word_dic)
    # 排序
    # print(sorted(word_dic.items(), key=lambda x: x[1], reverse=True))
    # 创建词云图
    creat_wordcloudImg(word_dic, column, word_num=200)

    words_data = {'word': [], 'amount': []}
    for t in word_dic:
        words_data['word'].append(t)
        words_data['amount'].append(word_dic[t])
    return pd.DataFrame(words_data).sort_values(by='amount', ascending=False)


titleword_df = word_count2df('title')
titleword_df

                  word  amount
1620          learning    8862
88               based    7379
85             quantum    6718
247              model    6609
604           networks    5575
...                ...     ...
35341      polyanlytic       1
35340          zn2sio4       1
35339           sympas       1
35338              smn       1
54429  nonintersecting       1

[54430 rows x 2 columns]

In [81]:
abstract_df = word_count2df('abstract')
abstract_df

                        word  amount
183                    paper   45637
50                     model   42407
26                     based   42190
369                     data   35637
329                    study   33393
...                      ...     ...
97230                rulison       1
97228   pasquero2016multiple       1
97227                  girds       1
97226                   419b       1
162167               0401148       1

[162168 rows x 2 columns]

# 2. 论文是否更新

In [82]:
taget2_df = readJsonFile('../arxiv-metadata-oai-2019.json', column=['id', 'versions'])
taget2_df

                  id                                           versions
0          0704.0297  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
1          0704.0342  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
2          0704.0360  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
3          0704.0525  [{'version': 'v1', 'created': 'Wed, 4 Apr 2007...
4          0704.0535  [{'version': 'v1', 'created': 'Wed, 4 Apr 2007...
...              ...                                                ...
169995  math/0603044  [{'version': 'v1', 'created': 'Thu, 2 Mar 2006...
169996  math/0603049  [{'version': 'v1', 'created': 'Thu, 2 Mar 2006...
169997  math/0603124  [{'version': 'v1', 'created': 'Sun, 5 Mar 2006...
169998  math/0603268  [{'version': 'v1', 'created': 'Mon, 13 Mar 200...
169999  math/0603276  [{'version': 'v1', 'created': 'Sun, 12 Mar 200...

[170000 rows x 2 columns]

In [88]:
import matplotlib.pyplot as plt

version_dic = {'id': [], 'version_num': []}
for i in range(len(taget2_df)):
    version_dic['id'].append(taget2_df['id'][i])
    version_dic['version_num'].append(str(len(list(taget2_df['versions'][i]))))
version_df = pd.DataFrame(version_dic)
version_dic = version_df.groupby('version_num').size().to_dict()
version_dic
# color = plt.get_cmap('Set3')(range(len(version_dic)))
#
# plt.pie(version_dic.values(), labels=version_dic.keys(), autopct='%0.1f%%', colors=color)
# plt.show()

{'1': 100528,
 '10': 28,
 '11': 21,
 '12': 19,
 '13': 8,
 '14': 7,
 '15': 4,
 '16': 3,
 '17': 2,
 '18': 2,
 '19': 3,
 '2': 46157,
 '20': 2,
 '21': 2,
 '22': 1,
 '24': 1,
 '27': 2,
 '3': 15630,
 '34': 1,
 '37': 1,
 '4': 4902,
 '5': 1652,
 '6': 606,
 '64': 1,
 '7': 257,
 '8': 112,
 '80': 1,
 '9': 47}

# 3.论文在 arxiv 系统中所属的类别统计

In [89]:
taget3_df = readJsonFile('../arxiv-metadata-oai-2019.json', column=['id', 'categories'])
taget3_df
# print(taget3_df['categories'][i])

                  id       categories
0          0704.0297         astro-ph
1          0704.0342          math.AT
2          0704.0360         astro-ph
3          0704.0525            gr-qc
4          0704.0535         astro-ph
...              ...              ...
169995  math/0603044          math.PR
169996  math/0603049  math.GT math.RT
169997  math/0603124          math.FA
169998  math/0603268          math.NT
169999  math/0603276  math.DG math.AG

[170000 rows x 2 columns]

In [95]:
categorie_num = {}


# 根据第三个级别的分类简写找出它所在的大类
def find_level1(level3, leveltabel):
    if len(leveltabel[leveltabel['categories'] == level3].values) == 0:
        level1 = leveltabel[leveltabel['archive_id'] == level3]['group_name']
    else:
        level1 = leveltabel[leveltabel['categories'] == level3]['group_name']
    if len(level1) == 0:
        return 'Not Exit'
    else:
        return level1.values[0]


leve_tabel = pd.read_csv('./categorys.csv')
for i in range(len(taget3_df)):
    for ctgr in taget3_df['categories'][i].split(' '):
        level1 = find_level1(ctgr, leve_tabel)
        if categorie_num.get(level1):
            categorie_num[level1] += 1
        else:
            categorie_num[level1] = 1
categorie_num

{'Physics': 117900,
 'Mathematics': 69775,
 'Computer Science': 78651,
 'Quantitative Biology': 3552,
 'Statistics': 18848,
 'Quantitative Finance': 1842,
 'Economics': 861,
 'Electrical Engineering and Systems Science': 8427,
 'Not Exit': 47}

In [99]:
group_df = {'group': [], 'number': []}
for group in categorie_num:
    group_df['group'].append(group)
    group_df['number'].append(categorie_num[group])
pd.DataFrame(group_df)

                                        group  number
0                                     Physics  117900
1                                 Mathematics   69775
2                            Computer Science   78651
3                        Quantitative Biology    3552
4                                  Statistics   18848
5                        Quantitative Finance    1842
6                                   Economics     861
7  Electrical Engineering and Systems Science    8427
8                                    Not Exit      47


3. 论文页数、图、表统计
4. 论文作者的个数
5. 谁提交的论文最多
6. 按月份统计每个月论文的提交数量